spring:
  application:
    name: mecash

  datasource:
    url: jdbc:postgresql://localhost:5432/mecash
    username: postgres
    password: Allah-110292$$

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

server:
  port: 8080